In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("elikplim/eergy-efficiency-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'eergy-efficiency-dataset' dataset.
Path to dataset files: /kaggle/input/eergy-efficiency-dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/kaggle/input/eergy-efficiency-dataset/ENB2012_data.csv')
df

       X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28
..    ...    ...    ...     ...  ...  ..  ...  ..    ...    ...
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5  17.88  21.40
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5  16.54  16.88
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5  16.44  17.11
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5  16.48  16.61
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5  16.64  16.03

[768 rows x 10 columns]

In [ ]:
df.columns=['Relative Compactness','Surface Area','Wall Area','Roof Area','Overall Height','Orientation',
            'Glazing Area','Glazing Area Distribution','Heating Load','Cooling load']
df

,Relative Compactness,Surface Area,Wall Area,Roof Area,Overall Height,Orientation,Glazing Area,Glazing Area Distribution,Heating Load,Cooling load
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84,28.28
...,...,...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.0,220.50,3.5,5,0.4,5,17.88,21.40
764,0.62,808.5,367.5,220.50,3.5,2,0.4,5,16.54,16.88
765,0.62,808.5,367.5,220.50,3.5,3,0.4,5,16.44,17.11
766,0.62,808.5,367.5,220.50,3.5,4,0.4,5,16.48,16.61
767,0.62,808.5,367.5,220.50,3.5,5,0.4,5,16.64,16.03

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Relative Compactness       768 non-null    float64
 1   Surface Area               768 non-null    float64
 2   Wall Area                  768 non-null    float64
 3   Roof Area                  768 non-null    float64
 4   Overall Height             768 non-null    float64
 5   Orientation                768 non-null    int64
 6   Glazing Area               768 non-null    float64
 7   Glazing Area Distribution  768 non-null    int64
 8   Heating Load               768 non-null    float64
 9   Cooling load               768 non-null    float64
dtypes: float64(8), int64(2)
memory usage: 60.1 KB

,Relative Compactness,Surface Area,Wall Area,Roof Area,Overall Height,Orientation,Glazing Area,Glazing Area Distribution,Heating Load,Cooling load
count,768.000000,768.000000,768.000000,768.000000,768.00000,768.000000,768.000000,768.00000,768.000000,768.000000
mean,0.764167,671.708333,318.500000,176.604167,5.25000,3.500000,0.234375,2.81250,22.307201,24.587760
std,0.105777,88.086116,43.626481,45.165950,1.75114,1.118763,0.133221,1.55096,10.090196,9.513306
min,0.620000,514.500000,245.000000,110.250000,3.50000,2.000000,0.000000,0.00000,6.010000,10.900000
25%,0.682500,606.375000,294.000000,140.875000,3.50000,2.750000,0.100000,1.75000,12.992500,15.620000
50%,0.750000,673.750000,318.500000,183.750000,5.25000,3.500000,0.250000,3.00000,18.950000,22.080000
75%,0.830000,741.125000,343.000000,220.500000,7.00000,4.250000,0.400000,4.00000,31.667500,33.132500
max,0.980000,808.500000,416.500000,220.500000,7.00000,5.000000,0.400000,5.00000,43.100000,48.030000

In [ ]:
df.isna().sum()
print("Nulls:",df.isnull().sum())

Nulls: Relative Compactness         0
Surface Area                 0
Wall Area                    0
Roof Area                    0
Overall Height               0
Orientation                  0
Glazing Area                 0
Glazing Area Distribution    0
Heating Load                 0
Cooling load                 0
dtype: int64

In [ ]:
X=df.drop(['Heating Load','Cooling load'],axis=1)
y=df[['Heating Load', 'Cooling load']]
X
y

     Heating Load  Cooling load
0           15.55         21.33
1           15.55         21.33
2           15.55         21.33
3           15.55         21.33
4           20.84         28.28
..            ...           ...
763         17.88         21.40
764         16.54         16.88
765         16.44         17.11
766         16.48         16.61
767         16.64         16.03

[768 rows x 2 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,accuracy_score

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
lr=LinearRegression()

lr.fit(X_train_scaled,y_train)

y_pred=lr.predict(X_test_scaled)
y_pred

array([[18.76970179, 19.50955347],
       [13.97718538, 16.59529257],
       [31.1689639 , 31.77268717],
       [35.89715871, 36.71917738],
       [15.31682963, 17.18185995],
       [28.65657438, 31.12311761],
       [24.93665201, 27.50711723],
       [27.94923139, 29.55976325],
       [17.63721067, 19.08326399],
       [27.568232  , 29.84078788],
       [18.02793729, 19.5136837 ],
       [34.31537863, 35.54815146],
       [27.72822584, 30.2207936 ],
       [ 8.59702323, 12.31621683],
       [18.56014178, 19.28491996],
       [36.8429128 , 37.6098334 ],
       [37.51153149, 37.87093929],
       [11.35529018, 14.42831276],
       [15.21614817, 17.43144289],
       [34.29179898, 35.65801537],
       [34.40384106, 35.39772347],
       [35.25211967, 36.34820758],
       [10.94102635, 14.65251046],
       [29.96631854, 32.17442971],
       [12.55856267, 15.06976402],
       [29.94273889, 32.28429362],
       [33.29191904, 34.22525765],
       [34.33310212, 35.7273152 ],
       [14.64821094, 16.92075406],
       [15.70996311, 17.67663528],
       [ 7.92840454, 12.05511094],
       [10.84666533, 14.5472126 ],
       [15.08609685, 17.13144596],
       [30.95337577, 33.13438556],
       [29.20338126, 32.35277946],
       [27.9020721 , 29.77949107],
       [30.86749218, 32.0518649 ],
       [29.22696091, 32.24291555],
       [33.26833939, 34.33512156],
       [ 8.96025663, 13.27573686],
       [28.59427044, 29.93073304],
       [11.37886983, 14.31844886],
       [ 6.73685736, 11.78364959],
       [32.38463936, 33.9501525 ],
       [ 7.43146257, 11.99924718],
       [ 6.71327772, 11.8935135 ],
       [ 8.69404744, 13.27028709],
       [ 8.98383628, 13.16587296],
       [28.93417407, 31.68681459],
       [30.94795835, 32.43371752],
       [33.52265182, 34.27567164],
       [14.90011649, 16.79694854],
       [14.13717922, 16.97529829],
       [32.88457933, 34.66653136],
       [12.84860783, 15.74976667],
       [12.30425025, 15.12921394],
       [10.89382463, 14.32748478],
       [31.82914759, 33.55576935],
       [40.29337809, 39.87317131],
       [37.07364558, 37.66024739],
       [16.53221277, 18.12787419],
       [19.23116734, 19.61038146],
       [14.82937755, 17.12654027],
       [28.84014786, 31.39325942],
       [28.57069079, 30.04059695],
       [29.8955796 , 32.50402143],
       [29.91915924, 32.39415753],
       [10.98818565, 14.43278264],
       [12.95169616, 15.56453934],
       [11.1245574 , 14.37789877],
       [27.05960715, 29.95968771],
       [31.63042946, 31.87351515],
       [13.59037233, 15.74563644],
       [28.17152917, 31.13215353],
       [32.15390658, 33.89973851],
       [10.87024498, 14.43734869],
       [34.81814733, 35.71827927],
       [31.41484133, 33.23521354],
       [30.70749835, 31.67185918],
       [23.74535472, 27.92235348],
       [25.42169722, 27.49808131],
       [32.95531827, 34.33693963],
       [ 9.42172219, 13.37656485],
       [15.78070205, 17.34704355],
       [11.42607156, 14.64347454],
       [15.9083465 , 17.58268487],
       [26.40663989, 29.62513265],
       [36.58860038, 37.66928331],
       [29.25054056, 32.13305164],
       [14.577472  , 17.25034579],
       [11.86636434, 14.91852204],
       [31.13694926, 33.40452737],
       [ 9.65486184, 13.49133445],
       [14.66938371, 16.74653455],
       [37.05006594, 37.7701113 ],
       [14.62222442, 16.96626236],
       [26.8916851 , 29.61609673],
       [29.88068483, 31.77860665],
       [ 9.69961426, 13.20725103],
       [ 9.00741592, 13.05600905],
       [39.60117976, 39.72192933],
       [27.67133932, 29.72907707],
       [ 7.69767176, 12.00469695],
       [28.02969756, 29.94161587],
       [29.41921927, 31.67777867],
       [18.53896901, 19.45913948],
       [27.8936371 , 31.30146736],
       [19.00043456, 19.55996747],
       [16.04716756, 18.13691011],
       [10.6395122 , 14.38693469],
       [33.80675378, 35.66705129],
       [32.91684386, 33.72138876],
       [24.70591924, 27.45670324],
       [17.38049137, 19.0783583 ],
       [11.07739811, 14.59762659],
       [15.19256852, 17.5413068 ],
       [10.29990088, 13.86230425],
       [ 8.15913732, 12.10552494],
       [13.56679268, 15.85550035],
       [24.81262824, 28.57746434],
       [27.79896478, 29.89120187],
       [10.53063366, 13.91271824],
       [31.32904209, 34.23441393],
       [15.47923033, 17.62622128],
       [27.31391958, 29.9002378 ],
       [18.48940284, 19.61451169],
       [16.30147999, 18.07746019],
       [30.12631238, 32.55443543],
       [25.39811757, 27.60794522],
       [39.57760011, 39.83179324],
       [22.45894032, 26.07447987],
       [34.24463969, 35.87774318],
       [15.50280998, 17.51635737],
       [14.13713678, 16.43054479],
       [15.16898887, 17.65117071],
       [18.28224971, 19.45423379],
       [32.84610492, 34.05098049],
       [35.87357906, 36.82904129],
       [13.83566506, 16.70972252],
       [17.8443638 , 19.24354189],
       [ 8.93667698, 13.38560077],
       [40.2462188 , 40.09289913],
       [28.3871173 , 29.77045514],
       [30.971538  , 32.32385361],
       [33.7533846 , 34.32608563],
       [11.19533878, 14.59306054],
       [ 8.3427108 , 12.37566675],
       [27.0360275 , 30.06955162],
       [33.98411738, 34.37649963],
       [32.42311377, 34.56570337],
       [33.03760661, 34.28470756],
       [29.23564579, 31.40763686],
       [29.00491301, 31.35722286],
       [12.6414547 , 15.58948877],
       [27.96437604, 30.97187563],
       [17.82078415, 19.3534058 ],
       [29.18848649, 31.62736467],
       [30.04860688, 32.12219764],
       [11.60964504, 14.91361635],
       [30.32649895, 31.95288381],
       [33.01402697, 34.39457147],
       [32.21596064, 34.40542547],
       [18.95327527, 19.77969529],
       [11.61205191, 14.97797196],
       [14.85536407, 17.08103197],
       [12.2806706 , 15.23907784],
       [28.3786823 , 31.29243144],
       [33.59960065, 35.50677339],
       [34.54611141, 35.59856545],
       [ 9.83843532, 13.76147626],
       [10.1068375 , 13.59161836],
       [33.576021  , 35.6166373 ],
       [ 8.62060288, 12.20635292],
       [31.37611704, 31.93296507],
       [13.20600859, 15.50508943],
       [35.71358522, 36.44903557],
       [11.14817948, 14.81278836],
       [14.57502269, 16.64123668],
       [34.0610662 , 35.60760137],
       [34.08464585, 35.49773746],
       [ 6.78401666, 11.56392177],
       [15.88717373, 17.75690439],
       [33.24475975, 34.44498547],
       [14.55144305, 16.75110059],
       [30.09576618, 31.90246982],
       [11.88994398, 14.80865813],
       [28.41069695, 29.66059123],
       [13.62851193, 16.54944462],
       [11.92567672, 15.5481107 ],
       [35.43569315, 36.61834939],
       [24.83620788, 28.46760043],
       [17.12617895, 19.13780821],
       [36.81933316, 37.71969731],
       [ 7.67409212, 12.11456086],
       [32.49385271, 34.23611165],
       [33.1624714 , 34.49721754],
       [25.16738479, 27.55753122],
       [13.54321304, 15.96536426],
       [27.64775967, 29.83894098],
       [11.21891842, 14.48319663],
       [14.91467645, 17.71062063],
       [33.47549252, 34.49539946],
       [18.92969562, 19.88955919],
       [29.39563963, 31.78764257],
       [ 9.41223229, 13.37602077],
       [34.38026141, 35.50758738],
       [28.19510882, 31.02228962],
       [28.61785008, 29.82086914],
       [26.01591328, 29.19471294],
       [12.59670227, 15.8735722 ],
       [34.61099419, 35.55800137],
       [17.84195693, 19.17918628],
       [18.30823623, 19.40872549],
       [30.6839187 , 31.78172309],
       [ 5.4742725 , 10.51260967],
       [13.3360599 , 15.80508636],
       [27.95895862, 30.27120759],
       [29.6263724 , 31.83805657],
       [31.11336961, 33.51439128],
       [13.90644644, 16.92488429],
       [28.14794953, 31.24201744],
       [ 9.63128219, 13.60119836],
       [24.65875994, 27.67643106],
       [32.93173862, 34.44680354],
       [18.51298249, 19.50464778],
       [15.60687478, 17.8618626 ],
       [17.79720451, 19.46326971],
       [27.75180549, 30.11092969],
       [31.94675345, 33.73946061],
       [14.62463129, 17.03061797],
       [30.90621648, 33.35411338]])

In [ ]:
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))

Mean Squared Error: 9.557319213902343
R-squared: 0.8994149873458704